// Optional integration runner: install Playwright or set PLAYWRIGHT_MODULE to
// an existing package path. PLAYWRIGHT_CHANNEL can select an installed browser.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdtemp, readFile, writeFile, rm, mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join, resolve, dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomBytes} from 'node:crypto';
const {chromium} = createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const directory = await mkdtemp(join(tmpdir(),'lifty-browser-'));
const token = randomBytes(32).toString('hex');
// Retired stores must not prevent current clients from syncing.
await writeFile(join(directory,'records.json'), JSON.stringify({'foods:legacy':{store:'foods',record:{id:'legacy'},version:'legacy'}}));
const child = spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:'5188',HOST:'127.0.0.1',SYNC_AUTH:'token',SYNC_TOKEN:token,APP_ORIGIN:'http://127.0.0.1:5188',DATA_DIR:directory},stdio:['ignore','pipe','pipe']});
let browser;
try {
  await new Promise((resolve,reject)=>{child.stdout.once('data',resolve);child.once('error',reject);child.once('exit',code=>reject(Error('Server exit '+code)));});
  browser = await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL || undefined});
  const context = await browser.newContext({viewport:{width:390,height:844},extraHTTPHeaders:{Authorization:'Bearer '+token},acceptDownloads:true});
  const page = await context.newPage();
  page.setDefaultTimeout(10000);
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('dialog',dialog=>dialog.accept());
  const go = async hash => {await page.evaluate(hash=>location.hash=hash,hash);await page.waitForFunction(hash=>location.hash===hash,hash);};
  const noOverflow = async () => assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true,'mobile horizontal overflow');
  const exported = async () => {
    await go('#settings');
    const download = page.waitForEvent('download');
    await page.locator('#export').click();
    return JSON.parse(await readFile(await (await download).path(),'utf8'));
  };
  await page.goto('http://127.0.0.1:5188/');
  await page.getByRole('heading',{name:'Today',exact:true}).waitFor();
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Synced with Pi'));
  await noOverflow();
  await page.evaluate(()=>navigator.serviceWorker.ready);
  await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
  await go('#workout/log');
  await page.locator('#workout-date').fill(new Date().toLocaleDateString('en-CA'));
  await page.locator('#workout-start button').click();
  await page.locator('[data-set="0,0,weight"]').fill('40');
  await page.locator('[data-set="0,0,reps"]').fill('8');
  await page.locator('[data-set="0,0,rir"]').fill('2');
  await page.locator('[data-set="0,0,done"]').check();
  await noOverflow();
  await page.locator('#finish').click();
  await page.locator('[data-session-edit]').click();
  await page.locator('[data-set="0,0,weight"]').fill('45');
  await page.locator('#session-cancel').click();
  assert.equal(await page.locator('[data-set="0,0,weight"]').inputValue(),'40');
  await page.locator('[data-session-edit]').click();
  await page.locator('[data-set="0,0,weight"]').fill('45');
  await page.locator('#session-save').click();
  await page.waitForFunction(()=>!document.querySelector('#session-save'));
  const sessionHash=await page.evaluate(()=>location.hash);
  await page.reload();
  await page.locator('[data-set="0,0,weight"]').waitFor();
  assert.equal(await page.locator('[data-set="0,0,weight"]').inputValue(),'45');
  await go('#progress/exercises');
  await page.locator('#progress-range').selectOption('0');
  await page.locator('#progress-metric').selectOption('volume');
  assert.match(await page.locator('.chart-title').textContent(),/Completed load-volume/);
  assert.equal(await page.locator('.chart-point').count(),1);
  await noOverflow();
  await go('#progress/body');
  await page.locator('#weight-entry summary').click();
  await page.locator('#weight-form [name=value]').fill('180');
  await page.locator('#weight-entry-unit').selectOption('kg');
  assert.ok(Math.abs(Number(await page.locator('#weight-form [name=value]').inputValue())-81.647)<0.001);
  await page.locator('#weight-form button').first().click();
  await page.waitForFunction(()=>!document.querySelector('#weight-entry').open);
  await go('#settings');
  await page.locator('#sync-now').click();
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Synced with Pi'));
  const weight = await page.evaluate(async()=>{const {readAll}=await import('/storage.js');return (await readAll('settings')).find(r=>r.type==='weighin');});
  await go('#progress/body');
  await page.getByText('Weight history · 1 entry',{exact:true}).click();
  await page.locator('[data-weight-edit]').click();
  await page.locator('#weight-form [name=value]').fill('82');
  // A second device changes this measurement while its editor remains open.
  const remote = await fetch('http://127.0.0.1:5188/api/sync',{method:'POST',headers:{Authorization:'Bearer '+token,Origin:'http://127.0.0.1:5188','Content-Type':'application/json'},body:JSON.stringify({changes:[{store:'settings',record:{...weight,note:'changed on another device'},base:weight._base}]})});
  assert.equal(remote.status,200);
  await page.evaluate(()=>window.dispatchEvent(new Event('online')));
  await page.waitForFunction(async()=>{const {readAll}=await import('/storage.js');return (await readAll('settings')).some(r=>r.note==='changed on another device');});
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Synced with Pi'));
  await page.locator('#weight-form button').first().click();
  await page.waitForFunction(()=>!document.querySelector('#weight-entry').open);
  await go('#settings');
  await page.locator('#sync-now').click();
  await page.waitForFunction(async()=>{const {readAll}=await import('/storage.js');return (await readAll('settings')).filter(r=>r.type==='weighin').length===2;});
  await go('#workout/routines');
  await page.locator('[data-edit-template="0"]').click();
  await page.locator('#editor-name').fill('Custom chest');
  await page.locator('#editor-save').click();
  await page.getByText('Custom chest',{exact:true}).waitFor();
  await noOverflow();
  await go('#settings');
  await page.locator('#preferences [name=unit]').selectOption('kg');
  await page.getByRole('button',{name:'Save preferences',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#preferences [name=increment]').value!=='2.5');
  const increment=await page.locator('#preferences [name=increment]').inputValue();
  await page.getByRole('button',{name:'Save preferences',exact:true}).click();
  assert.equal(await page.locator('#preferences [name=increment]').inputValue(),increment);
  const backup=await exported();
  assert.equal(backup.sessions.length,1);
  assert.equal(backup.weighIns.length,2);
  assert.ok(backup.weighIns.some(r=>r.conflictOf && r.value===82));
  assert.ok(backup.weighIns.some(r=>!r.conflictOf && r.note==='changed on another device'));
  assert.equal(backup.templates.length,1);
  // Reimporting the same backup must not invent conflicts from sync metadata.
  await page.locator('#import').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});
  await page.waitForFunction(()=>document.querySelector('#toast').textContent.startsWith('Backup merged'));
  assert.equal((await exported()).sessions.length,1);
  await go(sessionHash);
  await page.locator('[data-session-delete]').click();
  await page.locator('[data-confirm-delete]').click();
  await page.getByText('No sessions yet.',{exact:false}).waitFor();
  const deleted=await exported();
  assert.equal(deleted.sessions[0]._deleted,true);
  await page.locator('#import').setInputFiles({name:'old-backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});
  await page.waitForFunction(()=>document.querySelector('#toast').textContent.startsWith('Backup merged'));
  assert.equal((await exported()).sessions[0]._deleted,true);
  // Create and edit offline, reload the cached shell, then reconnect.
  await context.setOffline(true);
  await go('#workout/log');
  await page.locator('#workout-start button').click();
  await page.locator('[data-set="0,0,weight"]').fill('25');
  await page.waitForFunction(async()=>{const {readAll}=await import('/storage.js');return (await readAll('sessions')).some(s=>s.exercises[0].sets[0].weight==='25');});
  await page.reload();
  await page.locator('[data-set="0,0,weight"]').waitFor();
  assert.equal(await page.locator('[data-set="0,0,weight"]').inputValue(),'25');
  await context.setOffline(false);
  await go('#settings');
  await page.locator('#sync-now').click();
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Synced with Pi'));
  const disk=JSON.parse(await readFile(join(directory,'records.json'),'utf8'));
  assert.equal(disk['foods:legacy'].version,'legacy');
  assert.ok(Object.values(disk).some(item=>item.store==='sessions'&&!item.record._deleted&&item.record.exercises[0].sets[0].weight==='25'));
  await go('#today');
  for(const width of [320,390,768,1280]) {await page.setViewportSize({width,height:844});await noOverflow();}
  await page.setViewportSize({width:390,height:844});
  await mkdir(join(root,'dist'),{recursive:true});
  await page.screenshot({path:join(root,'dist','browser-smoke.png'),fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('Browser smoke passed: mobile layout, sync with retired records, logging, corrections, charts, weigh-ins, templates, preferences, backup merge, deletion, offline reload and reconnect.');
} finally {
  await browser?.close();
  const stopped=new Promise(resolve=>child.once('exit',resolve));
  if(child.exitCode===null) {child.kill();await stopped;}
  await rm(directory,{recursive:true,force:true});
}
